name: Devops CI Pipeline

on:
  push:
    branches:
      - practice_linux

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Repo Files
        run: ll

